name: check

on:
  push:
  schedule:
    - cron: '15 01 * * SUN'

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Set up JDK 11
      uses: actions/setup-java@v2.3.1
      with:
        java-version: 11
        distribution: 'adopt'
    - name: Setup Ubuntu
      run: |
        sudo apt-get -y update
        sudo apt-get -y -q install haveged
        sudo systemctl enable haveged
        sudo systemctl restart haveged
    - name: Gradle Wrapper Cache
      uses: actions/cache@v2.1.6
      with:
        path: ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle-wrapper.properties') }}
    - name: Gradle Dependencies Cache
      uses: actions/cache@v2.1.6
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-cache-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-cache-${{ hashFiles('**/*.gradle') }}
          ${{ runner.os }}-gradle-cache-
    - name: Gradle Check
      run: |
        ./gradlew -Dorg.gradle.console=plain --no-daemon clean check
